#!/bin/sh
#
# Usage: gputest.sh
# Change job name and email address as needed 
#        
# -- our name ---
#$ -N chi2_serial
#$ -S /bin/sh
# Make sure that the .e and .o file arrive in the
#working directory
#$ -cwd
#Merge the standard out and standard error to one file
#$ -j y
# Request a gpu
#$ -l gpu=1
/bin/echo Running on host: `hostname`.
/bin/echo In directory: `pwd`
/bin/echo Starting on: `date`
 
# Load CUDA module
. /opt/modules/init/bash
module load cuda

module load gsl-gnu4
export LD_LIBRARY_PATH=/opt/gsl/1.15/gnu4/lib:$LD_LIBRARY_PATH

#Full path to executable
#Replace usman's home directory path with yours in the command below
#/home/u/usman/courses/cs732_spring15/Chi8_v1/Chi8 /home/u/usman/chi8/1600/1/simdata1.txt 1600 1000 800 800 .05 0 > output

#/usr/bin/time -f %e -o serialtime ./chisquare_fs3 8000 29623 traindata trueclass > chiout

/usr/bin/time -f %e -o serialtime2 ./chisquare_fs3 4901 422006 /home/u/usman/courses/cs732_spring15/data/data_fixed_.01 /home/u/usman/courses/cs732_spring15/data/trueclass > chiout2

